const realName = {
    'pizza' : 'Pizza',
    'hamburguer' : 'Hambúrguer',
    'burrito' : 'Burrito',
    'Water' : 'Water Bottle',
    'refrigerante' : 'Water',
    'whisky' : 'Whisky',
    'leite2' : 'Garrafa de Leite (cheia)',
    'colete' : 'Armor',
    'taco' : 'Baseball Bat',
    'cassetete' : 'Cassetete',
    'faca' : 'Knife',
    'taser' : 'Taser',
    'glock' : 'Glock',
    'deagle' : 'Deagle',
    'escopeta' : 'ShotGun',
    'tec9' : 'Tec-9',
    'mp5' : 'MP5',
    'ak47' : 'AK-47',
    'm4a1' : 'M4A1',
    'awm' : 'AWM',
	'ak47boca' : 'Bocal AK-47',
	'ak47carregador' : 'Carregador AK-47',
	'ak47coronha' : 'Coronha AK-47',
	'ak47corpo' : 'Corpo AK-47',
	'escopetacoronha' : 'Coronha Escopeta',
	'corpoarma' : 'Corpo Arma',
	'glockcarregador' : 'Carregador Glock',
	'glockcorpo' : 'Corpo Glock',
	'glockslider' : 'Slider Glock',
	'tec9boca' : 'Bocal Tec-9',
	'tec9carregador' : 'Carregador Tec-9',
	'tec9corpo' : 'Corpo Tec-9',
	'capsula' : 'Capsula Vazia',
	'polvora' : 'Pólvora',
	'linha' : 'Linha de Costura',
	'agulha' : 'Agulha de Costura',
	'kevlar' : 'Kevlar',
    '.50' : 'Munição .50',
    '762' : '.762',
    '556' : '.556',
    '.45' : '.45',
    '12' : '12 Gauge',
    '9mm' : '9mm',
    'chip' : 'Chip',
    'picareta' : 'Picareta',
    'cutelo' : 'Cutelo',
    'pa' : 'Pá',
    'capacete' : 'Capacete',
    'Repaire-Kit' : 'Repaire Kit',
    'bandagem' : 'Bandages',
    'celular' : 'Celular',
    'cigarro' : 'Cigarro',
    'dado' : 'Dado',
    'cavalo' : 'Mask I',
    'caveira' : 'Máscara Caveira',
    'touro' : 'Mask II',
    'sacola' : 'Máscara Sacola',
    'criatura' : 'Máscara Criatura',
    'macaco' : 'Máscara Macaco',
    'porco' : 'Máscara Porco',
    'capeta' : 'Máscara Capeta',
    'flor' : 'Flowers',
    'som' : 'Caixa de Som',
    'presente' : 'Presente VIP',
    'gasolina' : 'Fuel Can',
    'leite1' : 'Garrafa de Leite (vazia)',
    'pneu' : 'Estepe de Veículo',
    'plastico' : 'Embalagem Plástica',
    'radinho' : 'Rádio Comunicador',
    'cocainaembalada' : 'Cocaina Embalada',
    'cocaina' : 'Cocaina Crua',
    'chaves' : 'Chaves',
    'seda' : 'Seda',
    'isqueiro' : 'Isqueiro',
    'algema' : 'Algema',
    'kitmedico' : 'Kit de Primeiros Socorros',
    'adrenalina' : 'Injeção de Adrenalina',
    'maleta' : 'Maleta',
    'fertilizante' : 'Fertilizante',
    'drill' : 'Furadeira Industrial',
    'lockpick' : 'Lock Pick',
    'dinheirosujo' : 'Dinheiro Sujo',
    'dinamite' : 'Dinamite',
    'pendrive' : 'Pen-Drive',
    'maconha2' : 'Bud de Maconha',
    'maconhaembalada' : 'Maconha Embalada',
    'ticket' : 'Ticket Premium',
    'ticket2' : 'Ticket Corrida',
    'cnh' : 'Habilitação',
    'identidade' : 'ID Card',
    'porte' : 'Gun License',
    'niobio' : 'Minério de Nióbio',
    'bronze' : 'Minério de Bronze',
    'prata' : 'Minério de Prata',
    'ouro' : 'Minério de Ouro',
    'diamante' : 'Minério de Diamante',
    'rubi' : 'Minério de Rubi',
}

const Icons = {
    'Item' : 'fa-solid fa-box',
    'Burger' : 'fa-solid fa-burger',
    'Water' : 'fa-solid fa-droplet',
    '.50 Ammo' : 'fa-solid fa-gun',
    'Bandage' : 'fa-solid fa-bandage',
    'Fuel Can' : 'fa-solid fa-gas-pump',
}

const maxAmount = {
    'a' : 10,
    'b' : 5,
}

const getKeyByValue = (object, value) => {
    return Object.keys(object).find(
        key => object[key] === value
    )
}

const getName = (method, item) => {
    if (method) {
        return realName[item]
    } else {
        return getKeyByValue(realName, item)
    }
}